server:
  port: 5003
spring:
  application:
    name: garbage-sorting-game-pk
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/garbage_sorting_game?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: 123
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    root: info